[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid
childlogdir=/run

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[eventlistener:required-service-exit]
command=/usr/local/lib/nymea-container/service-exit.py
events=PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
priority=1
startsecs=0
autorestart=true
stopwaitsecs=2
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork --nopidfile
priority=10
autorestart=false
startsecs=1
startretries=0
stopwaitsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:avahi]
command=/usr/local/lib/nymea-container/wait-service.py dbus /usr/sbin/avahi-daemon --no-chroot --no-rlimits --file=/usr/local/lib/nymea-container/avahi-daemon.conf
priority=20
autorestart=false
startsecs=1
startretries=0
stopwaitsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nymea]
command=/usr/local/lib/nymea-container/wait-service.py avahi /usr/bin/nymead -n
priority=30
autorestart=false
startsecs=1
startretries=0
stopwaitsecs=30
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
