version: '3'
services:
  nymead:
    build: .
    image: nymead-image
    container_name: nymea-docker
    privileged: true
    hostname: nymea-docker
    restart: on-failure:10
    ports:
      - "2222:2222" # nymea (tcp)
      - "2223:2223" # nymeas (ssl)
      - "2626:2626" # ws debug interface
      - "1883:1883" # mqtt
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - ./configs/nymea/etc:/etc/nymea/:rw
      - ./configs/nymea/data:/var/lib/nymea/:rw
      - ./configs/nymea/cache:/var/cache/nymea/:rw

  influxdb:
    image: influxdb:1.8.10
    environment:
      - INFLUXDB_MONITOR_STORE_ENABLED=false
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED=false
      - INFLUXDB_CONTINUOUS_QUERIES_QUERY_STATS_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    hostname: influxdb
    restart: on-failure:10
    ports:
      - 8086:8086
    volumes:
      - ./configs/influxdb/etc:/etc/influxdb/:rw
      - ./configs/influxdb/data:/var/lib/influxdb:rw
